import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>筋肉</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        ホゲホゲ
      </main>
    </div>
  )
}
